// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP _rcpp_module_boot_deprecated_module();
RcppExport SEXP _rcpp_module_boot_fis_module();
RcppExport SEXP _rcpp_module_boot_fisin_module();
RcppExport SEXP _rcpp_module_boot_fisout_module();
RcppExport SEXP _rcpp_module_boot_mf_module();
RcppExport SEXP _rcpp_module_boot_rule_module();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_deprecated_module", (DL_FUNC) &_rcpp_module_boot_deprecated_module, 0},
    {"_rcpp_module_boot_fis_module", (DL_FUNC) &_rcpp_module_boot_fis_module, 0},
    {"_rcpp_module_boot_fisin_module", (DL_FUNC) &_rcpp_module_boot_fisin_module, 0},
    {"_rcpp_module_boot_fisout_module", (DL_FUNC) &_rcpp_module_boot_fisout_module, 0},
    {"_rcpp_module_boot_mf_module", (DL_FUNC) &_rcpp_module_boot_mf_module, 0},
    {"_rcpp_module_boot_rule_module", (DL_FUNC) &_rcpp_module_boot_rule_module, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_FisPro(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
